# Pre-commit manager: https://pre-commit.com

# Commit hooks
repos:
  # Python security linter
  - repo: local
    hooks:
      # Python security linter
      - id: bandit
        name: Local bandit
        entry: bandit
        language: python
        types: [python]
        # ll: report only issues of a given severity level or higher (-l for LOW, -ll for MEDIUM, -lll for HIGH)
        # quiet: whether to only show output in the case of an error
        # -s B113: skip testing for timeouts in request calls.
        args: ["-ll", "--quiet", "-s", "B113"]
        stages: [commit, manual]
      # Python-code autoformat with minimum configuration
      - id: black
        name: Local black
        entry: black
        language: python
        types_or: [python, pyi]
        stages: [commit, manual]
        args: ["--line-length=120"]
      # Python-imports sorting. Settings are set in .isort.cfg
      - id: isort
        name: Local isort
        entry: isort
        language: python
        types_or: [python, pyi]
        args: ["--settings=pyproject.toml"]
        stages: [commit, manual]
      # Check typing in Python files. Settings are set in .mypy.ini
      - id: mypy
        name: Local mypy
        entry: mypy
        language: python
        types: [python]
        args: ["--config-file=pyproject.toml"]
        stages: [commit, manual]
      # Standard hooks available in the pre-commit-hook package
      # This hook checks yaml files for parseable syntax:
      - id: check-yaml
        name: Local check-yaml
        entry: check-yaml
        language: python
        types: [yaml]
        stages: [commit]
        args: [--unsafe]
      # Check for files that contain merge conflict strings:
      - id: check-merge-conflict
        name: Local check-merge-conflict
        entry: check-merge-conflict
        language: python
        types: [text]
        stages: [commit, manual]
      # This hook trims trailing whitespace:
      - id: trailing-whitespace-fixer
        name: Local trailing-whitespace-fixer
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        stages: [commit]
      # Forces LF over CRLF
      - id: mixed-line-ending
        name: Local mixed-line-ending
        entry: mixed-line-ending
        language: python
        types: [text]
        stages: [commit]
        args: ["--fix=lf"]
      # checks for files that would conflict in case-insensitive filesystems.
      - id: check-case-conflict
        name: Local check-case-conflict
        entry: check-case-conflict
        language: python
        stages: [commit]
      #  ensures that a file is either empty, or ends with one newline.
      - id: end-of-file-fixer
        name: Local end-of-file-fixer
        entry: end-of-file-fixer
        language: python
        types: [text]
        stages: [commit]
