[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 120
known_first_party=["scrap_utils"]

[tool.mypy]
ignore_missing_imports = true
pretty = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
